apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-configmap
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
data:
  viewer-pod-template.json: |-
    {
        "spec": {
            "serviceAccountName": "default-editor"
        }
    }
