apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    app: ml-pipeline-ui
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
