---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.pipeline.frontend.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.frontend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.pipeline.frontend.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http