---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - {{ .Values.istio.host | quote }}
  http:
    - match:
        - uri:
            prefix: /pipeline
      rewrite:
        uri: /pipeline
      route:
        - destination:
            host: ml-pipeline-ui.{{ include "kubeflow.namespace" . }}.svc.cluster.local
            port:
              number: 80
      timeout: 300s