apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: {{ include "kubeflow.namespace" . }}
stringData:
  accesskey: {{ .Values.pipeline.objectStore.accesskey }}
  secretkey: {{ .Values.pipeline.objectStore.secretkey }}