nameOverride: ""
fullnameOverride: ""

commonLabels: {}

imagePullSecrets: []

image:
  repository: "mpioperator/mpi-operator"
  tag: "0.4.0"
  pullPolicy: ""

serviceAccount:
  create: true
  name: ""

podLabels: {}

resources: {}

affinity: {}

tolerations: []

crds:
  install: true
