apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflow-oauth2-proxy
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/name: kubeflow-oauth2-proxy
data:
  oauth2-proxy.yaml: |-
    upstreamConfig:
      upstreams:
        - id: kubeflow-gateway
          path: /
          uri: http://kubeflow-gateway.{{ include "kubeflow.namespace" . }}.svc
    injectRequestHeaders:
      - name: {{ .Values.headers.userId }}
        values:
          - claim: email
    injectResponseHeaders:
      - name: {{ .Values.headers.userId }}
        values:
          - claim: email
    providers:
      {{- if .Values.oauth2Proxy.providers }}
      {{- toYaml .Values.oauth2Proxy.providers | nindent 6 }}
      {{- else }}
      []
      {{- end }}
    server:
      BindAddress: 0.0.0.0:4180
      SecureBindAddress: ""
    metricsServer:
      BindAddress: 0.0.0.0:44180
      SecureBindAddress: ""
