---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-oauth2-proxy
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/name: kubeflow-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeflow-oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeflow-oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
          args:
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --upstream=static://200
            - --set-xauthrequest=true
            {{- with .Values.oauth2Proxy.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: kubeflow-oauth2-proxy
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          readinessProbe:
            periodSeconds: 10
            httpGet:
              path: /ping
              port: 4180