---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-oauth2-proxy
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/name: kubeflow-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeflow-oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeflow-oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: {{ .Values.oauth2Proxy.image.repository }}:{{ .Values.oauth2Proxy.image.tag }}
          args:
            - --alpha-config=/etc/kubeflow-oauth2-proxy/oauth2-proxy.yaml
            - --silence-ping-logging
            {{- with .Values.oauth2Proxy.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: kubeflow-oauth2-proxy
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
            - name: metrics
              containerPort: 44180
              protocol: TCP
          volumeMounts:
            - name: kubeflow-oauth2-proxy
              mountPath: /etc/kubeflow-oauth2-proxy
              readOnly: true
          readinessProbe:
            periodSeconds: 10
            httpGet:
              path: /ping
              port: 4180
      volumes:
        - name: kubeflow-oauth2-proxy
          configMap:
            name: kubeflow-oauth2-proxy
            defaultMode: 0644
