apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-oauth2-proxy
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/name: kubeflow-oauth2-proxy
type: Opaque
data:
  {{- range $k, $v := .Values.oauth2Proxy.env }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}