{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
      - notebooks/finalizers
      - poddefaults
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
      - nodes
    verbs:
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-notebook-ui-admin
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-admin: "true"
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-notebook-ui-edit
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
      - notebooks/finalizers
      - poddefaults
    verbs:
      - get
      - list
      - create
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-notebook-ui-view
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
      - notebooks/finalizers
      - poddefaults
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
{{- end }}