{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-web-app-cluster-role-binding
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jupyter-web-app-cluster-role
subjects:
  - kind: ServiceAccount
    name: jupyter-web-app-service-account
    namespace: {{ include "kubeflow.namespace" . }}
{{- end }}