{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-config
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
data:
  spawner_ui_config.yaml: |
    {{- .Values.jupyterWebApp.spawnerUIConfig | toYaml | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-logos
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/jupyter-web-app/*" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-env
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
data:
  APP_PREFIX: /jupyter
  UI: default
  USERID_HEADER: {{ .Values.headers.userId | quote }}
  USERID_PREFIX: ""
  APP_SECURE_COOKIES: "true"
  CLUSTER_DOMAIN: cluster.local
{{- end }}