{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-web-app-deployment
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-web-app
      kustomize.component: jupyter-web-app
  template:
    metadata:
      labels:
        app: jupyter-web-app
        kustomize.component: jupyter-web-app
    spec:
      containers:
        # TODO: configmap
        - env:
            - name: APP_PREFIX
              value: /jupyter
            - name: UI
              value: default
            - name: USERID_HEADER
              value: x-auth-request-email
            - name: USERID_PREFIX
              value: ""
            - name: APP_SECURE_COOKIES
              value: "true"
          image: docker.io/kubeflownotebookswg/jupyter-web-app:v1.7.0-rc.0
          name: jupyter-web-app
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /src/apps/default/static/assets/logos
              name: logos-volume
      serviceAccountName: jupyter-web-app-service-account
      volumes:
        - configMap:
            name: jupyter-web-app-config
          name: config-volume
        - configMap:
            name: jupyter-web-app-logos
          name: logos-volume
{{- end }}