{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-web-app-jupyter-notebook-role-binding
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyter-web-app-jupyter-notebook-role
subjects:
  - kind: ServiceAccount
    name: jupyter-notebook
{{- end }}