{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-web-app-service-account
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
{{- end }}