{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
spec:
  host: {{ include "kubeflow.jupyterWebApp.fullname" . }}.{{ include "kubeflow.namespace" . }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - "*"
  http:
    - headers:
        request:
          add:
            x-forwarded-prefix: /jupyter
      match:
        - uri:
            prefix: /jupyter/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "kubeflow.jupyterWebApp.fullname" . }}.{{ include "kubeflow.namespace" . }}.svc.cluster.local
            port:
              number: 80

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "kubeflow.jupyterWebApp.matchLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/kubeflow-gateway
{{- end }}