{{- if .Values.tensorboardController.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.tensorboardController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.tensorboardController.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow.tensorboardController.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow.tensorboardController.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: {{ include "kubeflow.tensorboardController.fullname" . }}
      containers:
        - name: tensorboard-controller
          image: "{{ .Values.tensorboardController.image.repository }}:{{ .Values.tensorboardController.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
          ports:
            - name: https
              protocol: TCP
              containerPort: 443
            - name: http
              protocol: TCP
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.tensorboardController.fullname" . }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
        - name: kube-rbac-proxy
          image: "{{ .Values.tensorboardController.proxy.image.repository }}:{{ .Values.tensorboardController.proxy.image.tag }}"
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          ports:
            - name: https
              protocol: TCP
              containerPort: 8443
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      terminationGracePeriodSeconds: 10
{{- end }}