---
apiVersion: v1
kind: Service
metadata:
  name: metadata-grpc-service # metadata-grpc-envoy use this name to find the service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.metadataGRPC.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.pipeline.metadataGRPC.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: grpc-api
      port: 8080
      protocol: TCP
      targetPort: grpc-api

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.pipeline.metadataGRPC.envoy.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.metadataGRPC.envoy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.pipeline.metadataGRPC.envoy.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: md-envoy
      port: 9090
      protocol: TCP
      targetPort: md-envoy