---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeflow-gateway
  namespace: {{ include "kubeflow.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-gateway
subjects:
  - kind: ServiceAccount
    name: kubeflow-gateway
    namespace: {{ include "kubeflow.namespace" . }}