---
apiVersion: v1
kind: Service
metadata:
  name: kubeflow-gateway
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kubeflow-gateway
    istio: kubeflow-gateway
    app.kubernetes.io/name: kubeflow-gateway
    app.kubernetes.io/version: {{ .Values.istio.version | quote }}
spec:
  type: ClusterIP
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: kubeflow-gateway
    istio: kubeflow-gateway