apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeflow.pipeline.pipelineRunner.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.pipelineRunner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeflow.pipeline.pipelineRunner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeflow.pipeline.pipelineRunner.fullname" . }}
    namespace: {{ include "kubeflow.namespace" . }}
