---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      component: metadata-grpc-server