apiVersion: v1
kind: Service
metadata:
  name: metadata-envoy-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: metadata-envoy
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    application-crd-id: kubeflow-pipelines
    component: metadata-envoy
  type: ClusterIP
  ports:
    - name: md-envoy
      port: 9090
      protocol: TCP
