apiVersion: v1
kind: Service
metadata:
  name: metadata-grpc-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: metadata
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    application-crd-id: kubeflow-pipelines
    component: metadata-grpc-server
  type: ClusterIP
  ports:
    - name: grpc-api
      port: 8080
      protocol: TCP
