apiVersion: v1
kind: Service
metadata:
  name: cache-server
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: cache-server
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    app: cache-server
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  ports:
    - port: 443
      targetPort: webhook-api
