---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kfp-cache-cert
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: cache-server-cert-manager
spec:
  commonName: kfp-cache-cert
  dnsNames:
  - cache-server
  - cache-server.{{ include "kubeflow.namespace" . }}
  - cache-server.{{ include "kubeflow.namespace" . }}.svc
  isCA: true
  issuerRef:
    kind: Issuer
    name: kfp-cache-selfsigned-issuer
  secretName: webhook-server-tls

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kfp-cache-selfsigned-issuer
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: cache-server-cert-manager
spec:
  selfSigned: {}