apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cache-webhook-kubeflow
  annotations:
    cert-manager.io/inject-ca-from: {{ include "kubeflow.namespace" . }}/kfp-cache-cert
  labels:
    app: cache-server-cert-manager
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: cache-server
      namespace: {{ include "kubeflow.namespace" . }}
      path: /mutate
  failurePolicy: Ignore
  name: cache-server.{{ include "kubeflow.namespace" . }}.svc
  objectSelector:
    matchLabels:
      pipelines.kubeflow.org/cache_enabled: "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 5