apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.pipeline.cacheServer.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.cacheServer.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "kubeflow.pipeline.cacheServer.matchLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
