---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.pipeline.apiServer.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.apiServer.labels" . | nindent 4 }}