---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kubeflow.admissionWebhook.fullname" . }}
  labels:
    {{ include "kubeflow.admissionWebhook.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "kubeflow.namespace" . }}/{{ include "kubeflow.admissionWebhook.fullname" . }}
webhooks:
  - name: admission-webhook.kubeflow.org
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: kubeflow-profile
    admissionReviewVersions:
      - v1beta1
      - v1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      caBundle: ""
      service:
        name: {{ include "kubeflow.admissionWebhook.fullname" . }}
        namespace: {{ include "kubeflow.namespace" . }}
        path: /apply-poddefault