---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.admissionWebhook.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.admissionWebhook.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "kubeflow.admissionWebhook.matchLabels" . | nindent 4 }}
  ports:
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: https-webhook
