---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-gateway
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kubeflow-gateway
    istio: kubeflow-gateway
    app.kubernetes.io/name: kubeflow-gateway
    app.kubernetes.io/version: {{ .Values.istio.version | quote }}