---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubeflow-gateway
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/name: kubeflow-gateway
    app.kubernetes.io/version: {{ .Values.istio.version | quote }}
spec:
  gateways:
    - {{ .Values.istio.ingressGateway | quote }}
  hosts:
    - {{ .Values.istio.host | quote }}
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: kubeflow-gateway.{{ include "kubeflow.namespace" . }}.svc.cluster.local
            port:
              number: 80