{{- if .Values.tensorboardController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.tensorboardController.fullname" . }}
  labels:
    {{- include "kubeflow.tensorboardController.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - tensorboard.kubeflow.org
    resources:
      - tensorboards
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - tensorboard.kubeflow.org
    resources:
      - tensorboards/finalizers
    verbs:
      - update
  - apiGroups:
      - tensorboard.kubeflow.org
    resources:
      - tensorboards/status
    verbs:
      - get
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.tensorboardController.fullname" . }}-metrics
  labels:
    {{- include "kubeflow.tensorboardController.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.tensorboardController.fullname" . }}-proxy
  labels:
    {{- include "kubeflow.tensorboardController.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
{{- end }}