{{- if .Values.tensorboardController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.tensorboardController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.tensorboardController.labels" . | nindent 4 }}
{{- end }}