{{- if .Values.pvcViewerController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.pvcViewerController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pvcViewerController.labels" . | nindent 4 }}
{{- end }}