apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeflow.pipeline.persistenceAgent.fullname" . }}
  labels:
    {{- include "kubeflow.pipeline.persistenceAgent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - scheduledworkflows
      - workflows
    verbs:
      - report
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get