apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.pipeline.persistenceAgent.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.persistenceAgent.labels" . | nindent 4 }}
data:
  MULTIUSER: "true"