{{- if .Values.volumesWebApp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeflow.volumesWebApp.fullname" . }}
  labels:
    {{- include "kubeflow.volumesWebApp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeflow.volumesWebApp.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeflow.volumesWebApp.fullname" . }}
    namespace: {{ include "kubeflow.namespace" . }}
{{- end }}