{{- if .Values.volumesWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.volumesWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.volumesWebApp.labels" . | nindent 4 }}
{{- end }}