{{- if .Values.pvcViewerController.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kubeflow.pvcViewerController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pvcViewerController.labels" . | nindent 4 }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kubeflow.pvcViewerController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pvcViewerController.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: Issuer
    name: {{ include "kubeflow.pvcViewerController.fullname" . }}
  dnsNames:
    - {{ include "kubeflow.pvcViewerController.fullname" . }}.{{ include "kubeflow.namespace" . }}.svc
    - {{ include "kubeflow.pvcViewerController.fullname" . }}.{{ include "kubeflow.namespace" . }}.svc.cluster.local
  secretName: {{ include "kubeflow.pvcViewerController.fullname" . }}-certs
{{- end }}