{{- if .Values.volumesWebApp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.volumesWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.volumesWebApp.labels" . | nindent 4 }}
data:
  APP_PREFIX: /volumes
  USERID_HEADER: {{ .Values.headers.userId | quote }}
  USERID_PREFIX: ""
  APP_SECURE_COOKIES: "true"
  CLUSTER_DOMAIN: cluster.local
{{- end }}