---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.pipeline.metadataWriter.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.metadataWriter.labels" . | nindent 4 }}