---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: metadata-grpc-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  host: metadata-grpc-service.{{ include "kubeflow.namespace" . }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL