---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-grpc-configmap
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
    component: metadata-grpc-server
data:
  METADATA_GRPC_SERVICE_HOST: metadata-grpc-service
  METADATA_GRPC_SERVICE_PORT: "8080"
