---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: metadata-grpc
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  gateways:
    - {{ .Values.istio.gateway | quote }}
  hosts:
    - {{ .Values.istio.host | quote }}
  http:
    - match:
        - uri:
            prefix: /ml_metadata
      rewrite:
        uri: /ml_metadata
      route:
        - destination:
            host: metadata-envoy-service.{{ include "kubeflow.namespace" . }}.svc.cluster.local
            port:
              number: 9090