{{- if .Values.notebookController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notebook-controller-role-binding
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notebook-controller-role
subjects:
  - kind: ServiceAccount
    name: notebook-controller-service-account
    namespace: {{ include "kubeflow.namespace" . }}
{{- end }}