{{- if .Values.notebookController.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.notebookController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.notebookController.labels" . | nindent 4 }}
data:
  CLUSTER_DOMAIN: cluster.local
  CULL_IDLE_TIME: "1440"
  ENABLE_CULLING: "false"
  IDLENESS_CHECK_PERIOD: "1"
  ISTIO_GATEWAY: {{ include "kubeflow.namespace" . }}/kubeflow-gateway
  USE_ISTIO: "true"
{{- end }}