{{- if .Values.notebookController.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.notebookController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.notebookController.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "kubeflow.notebookController.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "kubeflow.notebookController.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.notebookController.fullname" . }}
      containers:
        - name: notebook-controller
          image: "{{ .Values.notebookController.image.repository }}:{{ .Values.notebookController.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          ports:
            - name: https
              protocol: TCP
              containerPort: 443
            - name: http
              protocol: TCP
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.notebookController.fullname" . }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}