{{- if .Values.notebookController.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notebook-controller-leader-election-rolebinding
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notebook-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: notebook-controller-service-account
    namespace: {{ include "kubeflow.namespace" . }}
{{- end }}