{{- if .Values.notebookController.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notebook-controller-leader-election-role
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
{{- end }}