{{- if .Values.notebookController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook-controller-service-account
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
{{- end }}