{{- if .Values.notebookController.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-controller-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
spec:
  ports:
    - port: 443
  selector:
    app: notebook-controller
    kustomize.component: notebook-controller
{{- end }}