{{- if .Values.notebookController.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.notebookController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{ include "kubeflow.notebookController.labels" . | nindent 4 }}
{{- end }}