nameOverride: ""
fullnameOverride: ""

commonLabels: {}

imagePullSecrets: []

image:
  repository: "ghcr.io/mellanox/k8s-rdma-shared-dev-plugin"
  tag: ""
  pullPolicy: ""

serviceAccount:
  create: true
  name: ""

podLabels: {}

resources: {}

tolerations: []

cdi:
  enabled: false

config:
  periodicUpdateInterval: 300
  configList:
    - resourceName: hca_shared_devices_a
      rdmaHcaMax: 1000
      devices:
        - ib0
        - ib1
    - resourceName: hca_shared_devices_b
      rdmaHcaMax: 500
      selectors:
        vendors:
          - 15b3
        deviceIDs:
          - "1017"
        ifNames:
          - ib3
          - ib4
