---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpiOperator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mpiOperator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mpiOperator.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "mpiOperator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mpiOperator.serviceAccountName" . }}
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          args:
            - -alsologtostderr
            - --lock-namespace={{ .Release.Namespace }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
