---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.accessManagement.fullname" . }}-namespace-labels
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.accessManagement.labels" . | nindent 4 }}
data:
  namespace-labels.yaml: |
    # Below is a list of labels to be set by default.
    #
    # To add a namespace label, use `key: 'value'`, for example:
    # istio.io/rev: 'asm-191-1'
    #
    # To remove a namespace label, use `key: ''`. For example:
    # istio-injection: ''
    #
    # Profile controller will not replace a namespace label if its key already
    # exists. If you want to override the value of a previously applied label, you
    # need to:
    # 1. Remove the label by using `key: ''` and deploy.
    # 2. Add the label by using `key: 'value'` and deploy.

    {{- if .Values.istio.revision }}
    istio-injection: ""
    istio.io/rev: {{ .Values.istio.revision }}
    {{- end }}

    # profile-controller
    pipelines.kubeflow.org/enabled: "true"

    # admission-webhook
    app.kubernetes.io/part-of: "kubeflow-profile"

    katib.kubeflow.org/metrics-collector-injection: "enabled"
    serving.kubeflow.org/inferenceservice: "enabled"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.accessManagement.fullname" . }}-env
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.accessManagement.labels" . | nindent 4 }}
data:
  ADMIN: {{ .Values.accessManagement.clusterAdmin | quote }}
  USERID_HEADER: {{ .Values.headers.userId | quote }}
  USERID_PREFIX: ""
  WORKLOAD_IDENTITY: ""
