---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.accessManagement.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.accessManagement.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.accessManagement.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: kfam-http