{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubeflow.jupyterWebApp.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow.jupyterWebApp.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.jupyterWebApp.fullname" . }}
      containers:
        - name: jupyter-web-app
          image:  "{{ .Values.jupyterWebApp.image.repository }}:{{ .Values.jupyterWebApp.image.tag }}"
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-env
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: logos-volume
              mountPath: /src/apps/default/static/assets/logos
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-config
        - name: logos-volume
          configMap:
            name: {{ include "kubeflow.jupyterWebApp.fullname" . }}-logos

{{- end }}