{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
{{- end }}