apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflow-pipelines-profile-controller-code
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
data:
  sync.py: |
    {{- range .Files.Lines "files/pipeline/sync.py" }}
    {{ . }}
    {{- end }}