apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.pipeline.profileController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.profileController.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubeflow.pipeline.profileController.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "kubeflow.pipeline.profileController.labels" . | nindent 8 }}
    spec:
      containers:
        - image: python:3.7
          name: profile-controller
          command:
            - python
            - /hooks/sync.py
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: KFP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: appVersion
                  name: pipeline-install-config
            - name: KFP_DEFAULT_PIPELINE_ROOT
              valueFrom:
                configMapKeyRef:
                  key: defaultPipelineRoot
                  name: pipeline-install-config
                  optional: true
            - name: OBJECT_STORE_HOST
              valueFrom:
                configMapKeyRef:
                  key: objectStoreHost
                  name: pipeline-install-config
            - name: OBJECT_STORE_PORT
              valueFrom:
                configMapKeyRef:
                  key: objectStorePort
                  name: pipeline-install-config
            - name: OBJECT_STORE_REGION
              valueFrom:
                configMapKeyRef:
                  key: objectStoreRegion
                  name: pipeline-install-config
                  optional: true
            - name: OBJECT_STORE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: objectStoreBucket
                  name: pipeline-install-config
            - name: OBJECT_STORE_KEY_FORMAT
              valueFrom:
                configMapKeyRef:
                  key: objectStoreKeyFormat
                  name: pipeline-install-config
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: mlpipeline-minio-artifact
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: mlpipeline-minio-artifact
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PIPELINE_SERVICEACCOUNT
              value: {{ include "kubeflow.pipeline.apiServer.fullname" . }}
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.pipeline.profileController.fullname" . }}-env
          volumeMounts:
            - name: hooks
              mountPath: /hooks
      volumes:
        - name: hooks
          configMap:
            name: {{ include "kubeflow.pipeline.profileController.fullname" . }}-sync-py
