apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow-pipelines-profile-controller
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kubeflow-pipelines-profile-controller
        app.kubernetes.io/component: ml-pipeline
        app.kubernetes.io/name: kubeflow-pipelines
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - command:
            - python
            - /hooks/sync.py
          env:
            - name: KFP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: appVersion
                  name: pipeline-install-config
            - name: KFP_DEFAULT_PIPELINE_ROOT
              valueFrom:
                configMapKeyRef:
                  key: defaultPipelineRoot
                  name: pipeline-install-config
                  optional: true
            - name: OBJECT_STORE_HOST
              valueFrom:
                configMapKeyRef:
                  key: objectStoreHost
                  name: pipeline-install-config
            - name: OBJECT_STORE_PORT
              valueFrom:
                configMapKeyRef:
                  key: objectStorePort
                  name: pipeline-install-config
            - name: OBJECT_STORE_REGION
              valueFrom:
                configMapKeyRef:
                  key: objectStoreRegion
                  name: pipeline-install-config
                  optional: true
            - name: OBJECT_STORE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: objectStoreBucket
                  name: pipeline-install-config
            - name: OBJECT_STORE_KEY_FORMAT
              valueFrom:
                configMapKeyRef:
                  key: objectStoreKeyFormat
                  name: pipeline-install-config
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: mlpipeline-minio-artifact
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: mlpipeline-minio-artifact
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: kubeflow-pipelines-profile-controller-env
          image: python:3.7
          name: profile-controller
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /hooks
              name: hooks
      volumes:
        - configMap:
            name: kubeflow-pipelines-profile-controller-code
          name: hooks
