apiVersion: v1
kind: Service
metadata:
  name: kubeflow-pipelines-profile-controller
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    app: kubeflow-pipelines-profile-controller
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
