---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: profiles-leader-election-rolebinding
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    kustomize.component: profiles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: profiles-leader-election-role
subjects:
  - kind: ServiceAccount
    name: profiles-controller-service-account
    namespace: {{ include "kubeflow.namespace" . }}
