---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: profiles-leader-election-role
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    kustomize.component: profiles
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create