---
apiVersion: v1
kind: Service
metadata:
  name: profiles-kfam
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    kustomize.component: profiles
spec:
  selector:
    kustomize.component: profiles
  ports:
    - port: 8081