{{- if .Values.tensorboardWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.tensorboardWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.tensorboardWebApp.labels" . | nindent 4 }}
{{- end }}