{{- define "kubeflow.pipeline.mysql.host" -}}
{{- if .Values.pipeline.mysql.enabled -}}
{{ include "kubeflow.pipeline.mysql.fullname" . }}.{{ include "kubeflow.namespace" . }}.svc.cluster.local
{{- else -}}
{{ .Values.pipeline.mysql.host }}
{{- end -}}
{{- end }}

{{- define "kubeflow.pipeline.mysql.port" -}}
{{- if .Values.pipeline.mysql.enabled -}}
3306
{{- else -}}
{{ .Values.pipeline.mysql.port }}
{{- end -}}
{{- end }}

{{- define "kubeflow.pipeline.mysql.user" -}}
{{- if .Values.pipeline.mysql.enabled -}}
root
{{- else -}}
{{ .Values.pipeline.mysql.user }}
{{- end -}}
{{- end }}

{{- define "kubeflow.pipeline.mysql.password" -}}
{{- if .Values.pipeline.mysql.enabled -}}

{{- else -}}
{{ .Values.pipeline.mysql.password }}
{{- end -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow.pipeline.mysql.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.mysql.labels" . | nindent 4 }}
data:
  host: {{ include "kubeflow.pipeline.mysql.host" . | b64enc }}
  port: {{ include "kubeflow.pipeline.mysql.port" . | b64enc }}
  user: {{ include "kubeflow.pipeline.mysql.user" . | b64enc }}
  {{- $password := include "kubeflow.pipeline.mysql.password" . -}}
  {{- if $password }}
  password: {{ b64enc $password }}
  {{- else }}
  password: ""
  {{- end }}
