{{- if .Values.pipeline.mysql.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.pipeline.mysql.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.mysql.labels" . | nindent 4 }}
{{- end }}