{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow.modelsWebApp.fullname" . }}-env
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.modelsWebApp.labels" . | nindent 4 }}
data:
  APP_PREFIX: /kserve-endpoints
  USERID_HEADER: {{ .Values.headers.userId | quote }}
{{- end }}