{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kserve-models-web-app-config
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    app.kubernetes.io/name: kserve
    kustomize.component: kserve-models-web-app
data:
  APP_PREFIX: /kserve-endpoints
  USERID_HEADER: {{ .Values.headers.userId }}
{{- end }}