{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-models-web-app
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    app.kubernetes.io/name: kserve
    kustomize.component: kserve-models-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserve
      app.kubernetes.io/component: kserve-models-web-app
      app.kubernetes.io/name: kserve
      kustomize.component: kserve-models-web-app
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: kserve
        app.kubernetes.io/component: kserve-models-web-app
        app.kubernetes.io/name: kserve
        kustomize.component: kserve-models-web-app
    spec:
      serviceAccountName: kserve-models-web-app
      containers:
        - name: kserve-models-web-app
          image: kserve/models-web-app:v0.10.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: kserve-models-web-app-config
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/liveness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/readiness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
{{- end }}