{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.modelsWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.modelsWebApp.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubeflow.modelsWebApp.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow.modelsWebApp.labels" . | nindent 8 }}
        {{- with .Values.modelsWebApp.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kubeflow.modelsWebApp.fullname" . }}
      containers:
        - name: models-web-app
          image: kserve/models-web-app:v0.10.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.modelsWebApp.fullname" . }}-env
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/liveness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz/readiness
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
{{- end }}