{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.modelsWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.modelsWebApp.labels" . | nindent 4 }}
{{- end }}