{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-models-web-app
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: kserve
    app.kubernetes.io/component: kserve-models-web-app
    app.kubernetes.io/name: kserve
    kustomize.component: kserve-models-web-app
{{- end }}