{{- if .Values.modelsWebApp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.modelsWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.modelsWebApp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.modelsWebApp.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
{{- end }}