---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeflow.pipeline.viewerController.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.viewerController.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - deployments
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - kubeflow.org
    resources:
      - viewers
      - viewers/finalizers
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
