---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rdmaSharedDevicePlugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rdmaSharedDevicePlugin.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
