---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "rdmaSharedDevicePlugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rdmaSharedDevicePlugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rdmaSharedDevicePlugin.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rdmaSharedDevicePlugin.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rdmaSharedDevicePlugin.serviceAccountName" . }}
      hostNetwork: true
      priorityClassName: system-node-critical
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
              readOnly: false
            - name: plugins-registry
              mountPath: /var/lib/kubelet/plugins_registry
              readOnly: false
            - name: config
              mountPath: /k8s-rdma-shared-dev-plugin
            - name: devs
              mountPath: /dev/
            {{- if .Values.cdi.enabled }}
            - name: dynamic-cdi
              mountPath: /var/lib/cdi
            {{- end }}
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: plugins-registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
        - name: config
          configMap:
            name: {{ include "rdmaSharedDevicePlugin.fullname" . }}
            items:
              - key: config.json
                path: config.json
        - name: devs
          hostPath:
            path: /dev/
        {{- if .Values.cdi.enabled }}
        - name: dynamic-cdi
          hostPath:
            path: /var/lib/cdi
            type: DirectoryOrCreate
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}