apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.pipeline.metadataWriter.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.metadataWriter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubeflow.pipeline.metadataWriter.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeflow.pipeline.metadataWriter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.pipeline.metadataWriter.fullname" . }}
      containers:
        - name: main
          image: "{{ .Values.pipeline.metadataWriter.image.repository }}:{{ .Values.pipeline.metadataWriter.image.tag }}"
          env:
            - name: NAMESPACE_TO_WATCH
              value: ""
