---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.pipeline.apiServer.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.apiServer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow.pipeline.apiServer.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        {{- include "kubeflow.pipeline.apiServer.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.pipeline.apiServer.fullname" . }}
      containers:
        - name: ml-pipeline-api-server
          image: "{{ .Values.pipeline.apiServer.image.repository }}:{{ .Values.pipeline.apiServer.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
            - name: grpc
              containerPort: 8887
              protocol: TCP
          env:
            - name: KUBEFLOW_USERID_HEADER
              value: {{ .Values.headers.userId }}
            - name: KUBEFLOW_USERID_PREFIX
              value: ""
            - name: AUTO_UPDATE_PIPELINE_DEFAULT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: autoUpdatePipelineDefaultVersion
                  name: pipeline-install-config
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OBJECTSTORECONFIG_SECURE
              valueFrom:
                configMapKeyRef:
                  key: objectStoreSecure
                  name: pipeline-install-config
            {{- if .Values.pipeline.objectStore.host }}
            - name: OBJECTSTORECONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  key: objectStoreHost
                  name: pipeline-install-config
            {{- end }}
            - name: OBJECTSTORECONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  key: objectStorePort
                  name: pipeline-install-config
            {{- if .Values.pipeline.objectStore.region }}
            - name: OBJECTSTORECONFIG_REGION
              valueFrom:
                configMapKeyRef:
                  key: objectStoreRegion
                  name: pipeline-install-config
            {{- end }}
            - name: OBJECTSTORECONFIG_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  key: objectStoreBucket
                  name: pipeline-install-config
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ include "kubeflow.pipeline.mysql.fullname" . }}
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "kubeflow.pipeline.mysql.fullname" . }}
            - name: DBCONFIG_DBNAME
              valueFrom:
                configMapKeyRef:
                  key: pipelineDb
                  name: pipeline-install-config
            - name: DBCONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  key: dbHost
                  name: pipeline-install-config
            - name: DBCONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  key: dbPort
                  name: pipeline-install-config
            - name: DBCONFIG_CONMAXLIFETIME
              valueFrom:
                configMapKeyRef:
                  key: ConMaxLifeTime
                  name: pipeline-install-config
            - name: OBJECTSTORECONFIG_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: mlpipeline-minio-artifact
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: mlpipeline-minio-artifact
          envFrom:
            - configMapRef:
                name: {{ include "kubeflow.pipeline.apiServer.fullname" . }}
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - "-"
                - http://localhost:8888/apis/v1beta1/healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - "-"
                - http://localhost:8888/apis/v1beta1/healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          startupProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - "-"
                - http://localhost:8888/apis/v1beta1/healthz
            failureThreshold: 12
            periodSeconds: 5
            timeoutSeconds: 2
