---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.apiServer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  selector:
    {{- include "kubeflow.pipeline.apiServer.matchLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 8887
      protocol: TCP
      targetPort: grpc
