{{- if .Values.volumeWebApp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volumes-web-app-parameters
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
data:
  APP_PREFIX: /volumes
  USERID_HEADER: {{ .Values.headers.userId | quote }}
  USERID_PREFIX: ""
  APP_SECURE_COOKIES: "true"
  CLUSTER_DOMAIN: cluster.local
{{- end }}