{{- if .Values.volumeWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-web-app-deployment
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumes-web-app
      kustomize.component: volumes-web-app
  template:
    metadata:
      labels:
        app: volumes-web-app
        kustomize.component: volumes-web-app
    spec:
      serviceAccountName: volumes-web-app-service-account
      containers:
        - image: docker.io/kubeflownotebookswg/volumes-web-app:v1.7.0-rc.0
          name: volumes-web-app
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: volumes-web-app-parameters
{{- end }}