{{- if .Values.volumeWebApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-web-app-deployment
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: volumes-web-app
    kustomize.component: volumes-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volumes-web-app
      kustomize.component: volumes-web-app
  template:
    metadata:
      labels:
        app: volumes-web-app
        kustomize.component: volumes-web-app
    spec:
      serviceAccountName: volumes-web-app-service-account
      containers:
        - env:
            - name: APP_PREFIX
              value: /volumes
            - name: USERID_HEADER
              value: {{ .Values.headers.userId | quote }}
            - name: USERID_PREFIX
              value: ""
            - name: APP_SECURE_COOKIES
              value: "true"
          image: docker.io/kubeflownotebookswg/volumes-web-app:v1.7.0-rc.0
          name: volumes-web-app
          ports:
            - containerPort: 5000
{{- end }}