---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  rules:
    - from:
        - source:
            namespaces:
              - istio-system
  selector:
    matchLabels:
      app: ml-pipeline-ui

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ml-pipeline
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-ui
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-persistenceagent
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-scheduledworkflow
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-viewer-crd-service-account
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/kubeflow-pipelines-cache
    - when:
        - key: request.headers[kubeflow-userid]
          notValues:
            - "*"
  selector:
    matchLabels:
      app: ml-pipeline

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ml-pipeline-visualizationserver
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-ui
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-persistenceagent
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-scheduledworkflow
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/ml-pipeline-viewer-crd-service-account
              - cluster.local/ns/{{ include "kubeflow.namespace" . }}/sa/kubeflow-pipelines-cache
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: service-cache-server
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  rules:
    - {}
  selector:
    matchLabels:
      app: cache-server

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: metadata-grpc-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      component: metadata-grpc-server

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  host: ml-pipeline-ui.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-pipeline
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  host: ml-pipeline.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-pipeline-visualizationserver
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
spec:
  host: ml-pipeline-visualizationserver.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: metadata-grpc-service
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  host: metadata-grpc-service.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
