apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
stringData:
  accesskey: minio
  secretkey: minio123