apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
stringData:
  username: root
  password: ""
