---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-pipelines-edit
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-edit: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipelines-edit: "true"
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-pipelines-view
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipelines-edit: "true"
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-view: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipelines-view: "true"
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-to-kubeflow-pipelines-edit
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipelines-edit: "true"
rules:
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - pipelines
      - pipelines/versions
    verbs:
      - create
      - delete
      - update
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - experiments
    verbs:
      - archive
      - create
      - delete
      - unarchive
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
    verbs:
      - archive
      - create
      - delete
      - retry
      - terminate
      - unarchive
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - jobs
    verbs:
      - create
      - delete
      - disable
      - enable
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - "*"
  - apiGroups:
      - argoproj.io
    resources:
      - cronworkflows
      - cronworkflows/finalizers
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workflowtemplates
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-to-kubeflow-pipelines-view
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
    rbac.authorization.kubeflow.org/aggregate-to-kubeflow-pipelines-view: "true"
rules:
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - pipelines
      - pipelines/versions
      - experiments
      - runs
      - jobs
    verbs:
      - get
      - list
  - apiGroups:
      - kubeflow.org
    resources:
      - viewers
    verbs:
      - create
      - get
      - delete
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - visualizations
    verbs:
      - create
