apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeflow.pipeline.visualizationServer.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.visualizationServer.labels" . | nindent 4 }}
