---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-pipeline-mysql
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  host: mysql.{{ include "kubeflow.namespace" . }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
