apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    application-crd-id: kubeflow-pipelines
spec:
  selector:
    app: mysql
    application-crd-id: kubeflow-pipelines
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
