metacontroller:
  enabled: true

istio:
  revision: ""
  version: "1.14.5"
  host: ""
  ingressGateway: "istio-system/ingress-gateway"

oauth2Proxy:
  extraArgs: []
  env: {}

pipeline:
  appVersion: 2.0.0-alpha.3
  apiServer:
    image:
      repository: gcr.io/ml-pipeline/api-server
      tag: 2.0.0-alpha.3
  persistenceAgent:
    image:
      repository: gcr.io/ml-pipeline/persistenceagent
      tag: 2.0.0-alpha.3
  scheduledWorkflow:
    image:
      repository: gcr.io/ml-pipeline/scheduledworkflow
      tag: 2.0.0-alpha.3
  frontend:
    image:
      repository: gcr.io/ml-pipeline/frontend
      tag: 2.0.0-alpha.3
  viewerCrdController:
    image:
      repository: gcr.io/ml-pipeline/viewer-crd-controller
      tag: 2.0.0-alpha.3
  visualizationServer:
    image:
      repository: gcr.io/ml-pipeline/visualization-server
      tag: 2.0.0-alpha.3
  cacheServer:
    image:
      repository: gcr.io/ml-pipeline/cache-server
      tag: 2.0.0-alpha.3

  objectStore:
    # S3
    # secure: "true"
    # host: "s3.amazonaws.com"
    # port: ""
    # region: us-west-2
    secure: "false"
    host: "minio.kubeflow"
    port: "9000"
    region: ""
    accesskey: "minio"
    secretkey: "minio123"
    bucketName: mlpipeline
    keyFormat: "artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}"

crds:
  install: true
