nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

commonLabels: {}

metacontroller:
  enabled: true

istio:
  revision: ""
  version: "1.16.1"
  host: ""
  ingressGateway:
    namespace: istio-system
    name: ingress-gateway

headers:
  userId: x-forwarded-email

oauth2Proxy:
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.4.0
  extraArgs:
    - --email-domain=*
  env: {}
  providers: []

pipeline:
  appVersion: 2.0.1
  apiServer:
    image:
      repository: gcr.io/ml-pipeline/api-server
      tag: 2.0.1
  persistenceAgent:
    image:
      repository: gcr.io/ml-pipeline/persistenceagent
      tag: 2.0.1
  scheduledWorkflow:
    image:
      repository: gcr.io/ml-pipeline/scheduledworkflow
      tag: 2.0.1
  frontend:
    image:
      repository: gcr.io/ml-pipeline/frontend
      tag: 2.0.1
  viewerCrdController:
    image:
      repository: gcr.io/ml-pipeline/viewer-crd-controller
      tag: 2.0.1
  visualizationServer:
    image:
      repository: gcr.io/ml-pipeline/visualization-server
      tag: 2.0.1
  cacheServer:
    image:
      repository: gcr.io/ml-pipeline/cache-server
      tag: 2.0.1
  metadataWriter:
    image:
      repository: gcr.io/ml-pipeline/metadata-writer
      tag: 2.0.1

  objectStore:
    # S3
    # secure: "true"
    # host: "s3.amazonaws.com"
    # port: ""
    # region: us-west-2
    secure: "false"
    host: "minio.kubeflow"
    port: "9000"
    region: ""
    accesskey: "minio"
    secretkey: "minio123"
    bucketName: mlpipeline
    keyFormat: "artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}"

volumeWebApp:
  enabled: true

notebookController:
  enabled: true

jupyterWebApp:
  enabled: true

modelsWebApp:
  enabled: true
  image:
    repository: kserve/models-web-app
    tag: v0.10.0

crds:
  install: true
