nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

commonLabels: {}

metacontroller:
  enabled: true

istio:
  revision: ""
  version: "1.16.1"
  host: ""
  ingressGateway:
    namespace: istio-system
    name: ingress-gateway

headers:
  userId: x-forwarded-email

oauth2Proxy:
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.5.0
  extraArgs:
    - --email-domain=*
  # ENV_KEY: ENV_VALUE
  env: {}
  providers: []

centralDashboard:
  image:
    repository: docker.io/kubeflownotebookswg/centraldashboard
    tag: v1.8.0

  links:
    # https://kevingleason.me/Polymer-Todo/bower_components/iron-icons/demo/index.html
    menuLinks:
      []
      # - type: "item"
      #   link: "/path"
      #   text: "text"
      #   icon: "icons:help"
    externalLinks: []
    quickLinks:
      []
      # - text: "title"
      #   desc: "description"
      #   link: "https://www.example.com"
    documentationItems:
      []
      # - text: "title"
      #   desc: "description"
      #   link: "https://www.example.com"

pipeline:
  appVersion: 2.0.3
  apiServer:
    image:
      repository: gcr.io/ml-pipeline/api-server
      tag: 2.0.3
  persistenceAgent:
    image:
      repository: gcr.io/ml-pipeline/persistenceagent
      tag: 2.0.3
  scheduledWorkflow:
    image:
      repository: gcr.io/ml-pipeline/scheduledworkflow
      tag: 2.0.3
  frontend:
    image:
      repository: gcr.io/ml-pipeline/frontend
      tag: 2.0.3
  viewerController:
    image:
      repository: gcr.io/ml-pipeline/viewer-crd-controller
      tag: 2.0.3
  visualizationServer:
    image:
      repository: gcr.io/ml-pipeline/visualization-server
      tag: 2.0.3
  cacheServer:
    image:
      repository: gcr.io/ml-pipeline/cache-server
      tag: 2.0.3
  metadataWriter:
    image:
      repository: gcr.io/ml-pipeline/metadata-writer
      tag: 2.0.3
  metadataGRPC:
    image:
      repository: gcr.io/tfx-oss-public/ml_metadata_store_server
      tag: 1.14.0

    envoy:
      image:
        repository: gcr.io/ml-pipeline/metadata-envoy
        tag: 2.0.3

  mysql:
    # If you want to use an existing mysql, set this to false and fill in
    # the connection info below.
    enabled: true

    # If pipeline.mysql.enabled is true, the following values are ignored.
    host: ""
    port: "3306"
    user: ""
    password: ""

  objectStore:
    # S3
    # secure: "true"
    # host: "s3.amazonaws.com"
    # port: ""
    # region: us-west-2
    secure: "false"
    host: "minio.kubeflow"
    port: "9000"
    region: ""
    accesskey: "minio"
    secretkey: "minio123"
    bucketName: mlpipeline
    keyFormat: "artifacts/{{workflow.name}}/{{workflow.creationTimestamp.Y}}/{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}/{{pod.name}}"

    defaultPipelineRoot: ""
    # If empty, defaultPipelineRoot will be used.
    defaultPipelineRootMultiUser: ""

accessManagement:
  kfam:
    image:
      repository: docker.io/kubeflownotebookswg/kfam
      tag: v1.8.0

  manager:
    image:
      repository: docker.io/kubeflownotebookswg/profile-controller
      tag: v1.8.0

  clusterAdmin: ""

admissionWebhook:
  image:
    repository: docker.io/kubeflownotebookswg/poddefaults-webhook
    tag: v1.8.0

volumesWebApp:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/volumes-web-app
    tag: v1.8.0

  volumeViewer:
    image:
      repository: filebrowser/filebrowser
      tag: v2.23.0

pvcViewerController:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/pvcviewer-controller
    tag: v1.8.0

notebookController:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/notebook-controller
    tag: v1.8.0

jupyterWebApp:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/jupyter-web-app
    tag: v1.8.0

  spawnerUIConfig:
    # --------------------------------------------------------------
    # Configuration file for the Kubeflow Notebooks UI.
    #
    # About the `readOnly` configs:
    #  - when `readOnly` is set to "true", the respective option
    #    will be disabled for users and only set by the admin
    #  - when 'readOnly' is missing, it defaults to 'false'
    # --------------------------------------------------------------
    spawnerFormDefaults:
      ################################################################
      # Container Images
      ################################################################
      # if users can input custom images, or only select from dropdowns
      allowCustomImage: true

      # if the registry of the container image is hidden from display
      hideRegistry: true

      # if the tag of the container image is hidden from display
      hideTag: false

      # configs for the ImagePullPolicy
      imagePullPolicy:
        readOnly: false

        # the default ImagePullPolicy
        # (possible values: "Always", "IfNotPresent", "Never")
        value: IfNotPresent

      ################################################################
      # Jupyter-like Container Images
      #
      # NOTES:
      #  - the `image` section is used for "Jupyter-like" apps whose
      #    HTTP path is configured by the "NB_PREFIX" environment variable
      ################################################################
      image:
        # the default container image
        value: kubeflownotebookswg/jupyter-scipy:v1.8.0

        # the list of available container images in the dropdown
        options:
          - kubeflownotebookswg/jupyter-scipy:v1.8.0
          - kubeflownotebookswg/jupyter-pytorch-full:v1.8.0
          - kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.8.0
          - kubeflownotebookswg/jupyter-tensorflow-full:v1.8.0
          - kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.8.0

      ################################################################
      # VSCode-like Container Images (Group 1)
      #
      # NOTES:
      #  - the `imageGroupOne` section is used for "VSCode-like" apps that
      #    expose themselves under the HTTP root path "/" and support path
      #    rewriting without breaking
      #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
      #    set on Notebooks spawned by this group, to make Istio rewrite
      #    the path of HTTP requests to the HTTP root
      ################################################################
      imageGroupOne:
        # the default container image
        value: kubeflownotebookswg/codeserver-python:v1.8.0

        # the list of available container images in the dropdown
        options:
          - kubeflownotebookswg/codeserver-python:v1.8.0

      ################################################################
      # RStudio-like Container Images (Group 2)
      #
      # NOTES:
      #  - the `imageGroupTwo` section is used for "RStudio-like" apps whose
      #    HTTP path is configured by the "X-RStudio-Root-Path" header
      #  - the annotation `notebooks.kubeflow.org/http-rewrite-uri: "/"` is
      #    set on Notebooks spawned by this group, to make Istio rewrite
      #    the path of HTTP requests to the HTTP root
      #  - the annotation `notebooks.kubeflow.org/http-headers-request-set` is
      #    set on Notebooks spawned by this group, such that Istio injects the
      #    "X-RStudio-Root-Path" header to all request
      ################################################################
      imageGroupTwo:
        # the default container image
        value: kubeflownotebookswg/rstudio-tidyverse:v1.8.0

        # the list of available container images in the dropdown
        options:
          - kubeflownotebookswg/rstudio-tidyverse:v1.8.0

      ################################################################
      # CPU Resources
      ################################################################
      cpu:
        readOnly: false

        # the default cpu request for the container
        value: "0.5"

        # a factor by which to multiply the CPU request calculate the cpu limit
        # (to disable cpu limits, set as "none")
        limitFactor: "1.2"

      ################################################################
      # Memory Resources
      ################################################################
      memory:
        readOnly: false

        # the default memory request for the container
        value: "1.0Gi"

        # a factor by which to multiply the memory request calculate the memory limit
        # (to disable memory limits, set as "none")
        limitFactor: "1.2"

      ################################################################
      # GPU/Device-Plugin Resources
      ################################################################
      gpus:
        readOnly: false

        # configs for gpu/device-plugin limits of the container
        # https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#using-device-plugins
        value:
          # the `limitKey` of the default vendor
          # (to have no default, set as "")
          vendor: ""

          # the list of available vendors in the dropdown
          #  `limitsKey` - what will be set as the actual limit
          #  `uiName` - what will be displayed in the dropdown UI
          vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"

          # the default value of the limit
          # (possible values: "none", "1", "2", "4", "8")
          num: "none"

      ################################################################
      # Workspace Volumes
      ################################################################
      workspaceVolume:
        readOnly: false

        # the default workspace volume to be created and mounted
        # (to have no default, set `value: null`)
        value:
          mount: /home/jovyan

          # pvc configs for creating new workspace volumes
          # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaim-v1-core
          newPvc:
            metadata:
              # "{notebook-name}" is replaced with the Notebook name
              name: "{notebook-name}-workspace"
            spec:
              #storageClassName: my-storage-class
              resources:
                requests:
                  storage: 5Gi
              accessModes:
                - ReadWriteOnce

      ################################################################
      # Data Volumes
      ################################################################
      dataVolumes:
        readOnly: false

        # a list of additional data volumes to be created and/or mounted
        value: []
        #value:
        #  - mount: /home/jovyan/datavol-1
        #    newPvc:
        #      metadata:
        #        name: "{notebook-name}-datavol-1"
        #      spec:
        #        resources:
        #          requests:
        #            storage: 5Gi
        #        accessModes:
        #          - ReadWriteOnce
        #
        #  - mount: /home/jovyan/datavol-1
        #    existingSource:
        #      persistentVolumeClaim:
        #        claimName: "test-pvc"

      ################################################################
      # Affinity
      ################################################################
      affinityConfig:
        readOnly: false

        # the `configKey` of the default affinity config
        # (to have no default, set as "")
        # (if `readOnly`, the default `value` will be the only accessible option)
        value: ""

        # the list of available affinity configs in the dropdown
        options: []
        #options:
        #  - configKey: "dedicated_node_per_notebook"
        #    displayName: "Dedicated Node Per Notebook"
        #    affinity:
        #      # Require a Node with label `lifecycle=kubeflow-notebook`
        #      nodeAffinity:
        #        requiredDuringSchedulingIgnoredDuringExecution:
        #          nodeSelectorTerms:
        #            - matchExpressions:
        #                - key: "lifecycle"
        #                  operator: "In"
        #                  values:
        #                    - "kubeflow-notebook"
        #
        #      # Require a Node WITHOUT an existing Pod having `notebook-name` label
        #      podAntiAffinity:
        #        requiredDuringSchedulingIgnoredDuringExecution:
        #          - labelSelector:
        #              matchExpressions:
        #                - key: "notebook-name"
        #                  operator: "Exists"
        #            topologyKey: "kubernetes.io/hostname"
        #            # WARNING: `namespaceSelector` is Beta in 1.22 and Stable in 1.24,
        #            #          setting to {} is required for affinity to work across Namespaces
        #            namespaceSelector: {}

      ################################################################
      # Tolerations
      ################################################################
      tolerationGroup:
        readOnly: false

        # the `groupKey` of the default toleration group
        # (to have no default, set as "")
        # (if `readOnly`, the default `value` will be the only accessible option)
        value: ""

        # the list of available toleration groups in the dropdown
        options: []
        #options:
        #  - groupKey: "group_1"
        #    displayName: "4 CPU 8Gb Mem at ~$X.XXX USD per day"
        #    tolerations:
        #      - key: "dedicated"
        #        operator: "Equal"
        #        value: "kubeflow-c5.xlarge"
        #        effect: "NoSchedule"
        #
        #  - groupKey: "group_2"
        #    displayName: "8 CPU 16Gb Mem at ~$X.XXX USD per day"
        #    tolerations:
        #      - key: "dedicated"
        #        operator: "Equal"
        #        value: "kubeflow-c5.2xlarge"
        #        effect: "NoSchedule"
        #
        #  - groupKey: "group_3"
        #    displayName: "16 CPU 32Gb Mem at ~$X.XXX USD per day"
        #    tolerations:
        #      - key: "dedicated"
        #        operator: "Equal"
        #        value: "kubeflow-c5.4xlarge"
        #        effect: "NoSchedule"
        #
        #  - groupKey: "group_4"
        #    displayName: "32 CPU 256Gb Mem at ~$X.XXX USD per day"
        #    tolerations:
        #      - key: "dedicated"
        #        operator: "Equal"
        #        value: "kubeflow-r5.8xlarge"
        #        effect: "NoSchedule"

      ################################################################
      # Shared Memory
      ################################################################
      shm:
        readOnly: false

        # the default state of the "Enable Shared Memory" toggle
        value: true

      ################################################################
      # PodDefaults
      ################################################################
      configurations:
        readOnly: false

        # the list of PodDefault names that are selected by default
        # (take care to ensure these PodDefaults exist in Profile Namespaces)
        value: []
        #value:
        #  - my-pod-default

      ################################################################
      # Environment
      #
      # NOTE:
      #  - these configs are only used by the ROK "flavor" of the UI
      ################################################################
      environment:
        readOnly: false
        value: {}

modelsWebApp:
  enabled: true
  image:
    repository: kserve/models-web-app
    tag: v0.10.0

tensorboardController:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/tensorboard-controller
    tag: v1.8.0

  proxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.8.0

  tensorboard:
    image:
      repository: tensorflow/tensorflow
      tag: 2.5.1

tensorboardWebApp:
  enabled: true
  image:
    repository: docker.io/kubeflownotebookswg/tensorboards-web-app
    tag: v1.8.0

crds:
  install: true
