apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.pipeline.scheduledWorkflow.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.scheduledWorkflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow.pipeline.scheduledWorkflow.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        {{- include "kubeflow.pipeline.scheduledWorkflow.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.pipeline.scheduledWorkflow.fullname" . }}
      containers:
        - name: scheduledworkflow
          image: "{{ .Values.pipeline.scheduledWorkflow.image.repository }}:{{ .Values.pipeline.scheduledWorkflow.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: ""
            - name: CRON_SCHEDULE_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  key: cronScheduleTimezone
                  name: pipeline-install-config
