apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeflow-pipelines-cache-deployer-role
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    app: cache-deployer
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - patch
      - list
