{{- if .Values.jupyterWebApp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow.jupyterWebApp.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.jupyterWebApp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.jupyterWebApp.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
{{- end }}