---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeflow.pipeline.visualizationServer.fullname" . }}
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.visualizationServer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow.pipeline.visualizationServer.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        {{- include "kubeflow.pipeline.visualizationServer.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeflow.pipeline.visualizationServer.fullname" . }}
      containers:
        - name: visualizationserver
          image: "{{ .Values.pipeline.visualizationServer.image.repository }}:{{ .Values.pipeline.visualizationServer.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - "-"
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - wget
                - -q
                - -S
                - -O
                - "-"
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 30m
              memory: 500Mi
