---
apiVersion: v1
kind: Service
metadata:
  name: ml-pipeline-visualizationserver
  namespace: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.pipeline.visualizationServer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubeflow.pipeline.visualizationServer.matchLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http